name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  industrial_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ROS_DISTRO: [noetic]
        ROS_REPO: [testing, main]
    env: 
      ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
      ROS_REPO: ${{ matrix.ROS_REPO }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Source tests
        uses: 'ros-industrial/industrial_ci@master'
        env:
          DOWNSTREAM_WORKSPACE: 'github:LeoRover/leo_robot#master github:LeoRover/leo_desktop#master'
          CATKIN_LINT: true
